"""CLI command: introspect a PostgreSQL schema and emit Ferrum model definitions.

Reads ``information_schema`` for column definitions, primary keys, and FK
constraints then maps each PostgreSQL type to the equivalent Ferrum
annotation.  Output is written to stdout or to a file / directory tree.

Security invariants:
- No credentials, bound values, or row data appear in emitted code or output.
- All queries use parameterised ``$1`` placeholders — schema name is the only
  variable and is never interpolated into an identifier position.
- ``ferrum_migrations`` and system tables (``pg_*``) are excluded by the query.
"""

from __future__ import annotations

import asyncio
import textwrap
from collections import defaultdict
from pathlib import Path

import typer

from ferrum.connection import connect
from ferrum.errors import FerrumConfigError

# ---------------------------------------------------------------------------
# PostgreSQL → Ferrum type mapping
# ---------------------------------------------------------------------------

_HEADER = textwrap.dedent("""\
    # Generated by ferrum inspectdb
    # Review and adjust before committing — this is a starting point, not final.

    from __future__ import annotations
    from datetime import date, datetime, time
    from decimal import Decimal
    from typing import Annotated
    from uuid import UUID

    import ferrum
    from ferrum import Field, ForeignKey, Model
""")


def _to_class_name(table_name: str) -> str:
    """Convert snake_case table name to PascalCase class name."""
    return "".join(part.capitalize() for part in table_name.split("_"))


def _pg_type_to_ferrum(
    pg_type: str,
    max_len: int | None,
    precision: int | None,
    scale: int | None,
    is_pk: bool,
    is_nullable: bool,
) -> str:
    """Return the Ferrum annotation string for a PostgreSQL column type.

    The returned string is the right-hand side of the type annotation,
    e.g. ``"str"``, ``"Annotated[str, Field(max_length=100)]"``, or
    ``"datetime | None"``.

    ``is_pk`` affects the annotation only for integer PKs (explicit
    ``Field(primary_key=True)`` is rendered on those).  FK columns are
    handled separately in the caller.
    """
    pg = pg_type.lower()

    if pg in (
        "integer",
        "int",
        "int4",
        "serial",
        "bigint",
        "bigserial",
        "int8",
        "smallint",
        "int2",
        "smallserial",
    ):
        base = "int"
    elif pg in ("boolean", "bool"):
        base = "bool"
    elif pg in ("real", "float4", "double precision", "float8", "float"):
        base = "float"
    elif pg in ("text", "character"):
        base = "str"
    elif pg == "character varying":
        base = f"Annotated[str, Field(max_length={max_len})]" if max_len is not None else "str"
    elif pg in ("numeric", "decimal"):
        if precision is not None and scale is not None:
            base = f"Annotated[Decimal, Field(max_digits={precision}, decimal_places={scale})]"
        else:
            base = "Decimal"
    elif pg in (
        "timestamp with time zone",
        "timestamptz",
        "timestamp without time zone",
        "timestamp",
    ):
        base = "datetime"
    elif pg == "date":
        base = "date"
    elif pg in ("time", "time without time zone", "time with time zone"):
        base = "time"
    elif pg == "uuid":
        base = "UUID"
    elif pg == "bytea":
        base = "bytes"
    elif pg in ("jsonb", "json"):
        base = "dict"
    else:
        base = f"str  # TODO: unsupported type {pg_type}"

    if is_nullable:
        # Wrap: if base already has spaces (e.g. a comment), keep it readable.
        if "  #" in base:
            core, comment = base.split("  #", 1)
            base = f"{core.strip()} | None  #{comment}"
        else:
            base = f"{base} | None"

    return base


# ---------------------------------------------------------------------------
# Async introspection queries
# ---------------------------------------------------------------------------

_COL_QUERY = """\
SELECT table_name, column_name, data_type, character_maximum_length,
       numeric_precision, numeric_scale, is_nullable, column_default,
       ordinal_position
FROM information_schema.columns
WHERE table_schema = $1 AND table_name != 'ferrum_migrations'
ORDER BY table_name, ordinal_position
"""

_FK_QUERY = """\
SELECT
    kcu.table_name, kcu.column_name,
    ccu.table_name  AS foreign_table_name,
    ccu.column_name AS foreign_column_name,
    rc.delete_rule
FROM information_schema.key_column_usage kcu
JOIN information_schema.referential_constraints rc
    ON kcu.constraint_name = rc.constraint_name
JOIN information_schema.constraint_column_usage ccu
    ON rc.unique_constraint_name = ccu.constraint_name
WHERE kcu.table_schema = $1
"""

_PK_QUERY = """\
SELECT kcu.table_name, kcu.column_name
FROM information_schema.key_column_usage kcu
JOIN information_schema.table_constraints tc
    ON kcu.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'PRIMARY KEY' AND kcu.table_schema = $1
"""


# ---------------------------------------------------------------------------
# Code rendering
# ---------------------------------------------------------------------------


def _render_class(
    table_name: str,
    columns: list[dict],
    pk_cols: set[str],
    fk_map: dict[str, dict],
) -> str:
    """Return a class definition string for a single table.

    Args:
        table_name: PostgreSQL table name.
        columns: Ordered list of column dicts (from information_schema).
        pk_cols: Set of column names that are primary keys for this table.
        fk_map: Mapping column_name → FK info dict (foreign_table_name,
            foreign_column_name, delete_rule).
    """
    class_name = _to_class_name(table_name)
    lines: list[str] = [f"class {class_name}(Model):"]

    for col in columns:
        col_name: str = col["column_name"]
        pg_type: str = col["data_type"]
        max_len: int | None = col["character_maximum_length"]
        precision: int | None = col["numeric_precision"]
        scale: int | None = col["numeric_scale"]
        is_nullable: bool = col["is_nullable"] == "YES"
        is_pk = col_name in pk_cols

        if col_name in fk_map:
            fk = fk_map[col_name]
            target_class = _to_class_name(fk["foreign_table_name"])
            delete_rule = fk["delete_rule"].upper()
            # Strip the trailing ``_id`` suffix for the field name if present.
            field_name = col_name[:-3] if col_name.endswith("_id") else col_name
            lines.append(
                f'    {field_name}: ForeignKey = ForeignKey(to="{target_class}",'
                f' on_delete="{delete_rule}")'
            )
            continue

        annotation = _pg_type_to_ferrum(pg_type, max_len, precision, scale, is_pk, is_nullable)

        if is_pk:
            # Emit the PK field with explicit Field(primary_key=True).
            # Strip any trailing ``| None`` from PK — PKs are never nullable.
            annotation = annotation.replace(" | None", "")
            lines.append(f"    {col_name}: {annotation} = Field(primary_key=True)")
        elif "Field(" in annotation:
            # Annotated[T, Field(...)] form — assign as bare annotation.
            lines.append(f"    {col_name}: {annotation}")
        else:
            lines.append(f"    {col_name}: {annotation}")

    if len(lines) == 1:
        lines.append("    ...")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main async entry point
# ---------------------------------------------------------------------------


async def run_inspectdb(
    *,
    output: Path | None = None,
    schema: str = "public",
) -> int:
    """Introspect a PostgreSQL schema and print Ferrum model definitions.

    Args:
        output: File path or directory to write generated code to.  If
            ``None``, writes to stdout.  A directory causes one file per
            table (``{table}_model.py``); a file path collects all classes.
        schema: PostgreSQL schema to introspect (default ``"public"``).

    Returns:
        Exit code: ``0`` on success, ``2`` on configuration/connection error.
    """
    try:
        async with connect() as conn:
            pool = conn._require_pool()
            async with pool.acquire() as db_conn:
                col_rows = await db_conn.fetch(_COL_QUERY, schema)
                fk_rows = await db_conn.fetch(_FK_QUERY, schema)
                pk_rows = await db_conn.fetch(_PK_QUERY, schema)
    except FerrumConfigError as exc:
        print(f"Configuration error: {exc}")
        return 2
    except Exception as exc:
        print(f"Connection error: {type(exc).__name__} [FERR-E101]")
        return 2

    # --- Build lookup structures ---

    # pk_cols_by_table: table_name → set of pk column names
    pk_cols_by_table: dict[str, set[str]] = defaultdict(set)
    for row in pk_rows:
        pk_cols_by_table[row["table_name"]].add(row["column_name"])

    # fk_by_table: table_name → {column_name: fk info dict}
    fk_by_table: dict[str, dict[str, dict]] = defaultdict(dict)
    for row in fk_rows:
        fk_by_table[row["table_name"]][row["column_name"]] = {
            "foreign_table_name": row["foreign_table_name"],
            "foreign_column_name": row["foreign_column_name"],
            "delete_rule": row["delete_rule"],
        }

    # cols_by_table: table_name → ordered list of column dicts
    cols_by_table: dict[str, list[dict]] = defaultdict(list)
    for row in col_rows:
        cols_by_table[row["table_name"]].append(dict(row))

    tables = list(cols_by_table.keys())

    if not tables:
        print(f"No tables found in schema {schema!r}.")
        return 0

    # --- Render class definitions ---

    if output is not None and output.is_dir():
        # One file per table.
        for table in tables:
            class_src = _render_class(
                table,
                cols_by_table[table],
                pk_cols_by_table.get(table, set()),
                fk_by_table.get(table, {}),
            )
            dest = output / f"{table}_model.py"
            dest.write_text(_HEADER + "\n\n" + class_src + "\n")
            print(f"  wrote {dest}")
        return 0

    # Single file or stdout.
    classes = [
        _render_class(
            table,
            cols_by_table[table],
            pk_cols_by_table.get(table, set()),
            fk_by_table.get(table, {}),
        )
        for table in tables
    ]
    full_src = _HEADER + "\n\n" + "\n\n\n".join(classes) + "\n"

    if output is None:
        print(full_src, end="")
    else:
        output.write_text(full_src)
        print(f"  wrote {output}")

    return 0


# ---------------------------------------------------------------------------
# Sync dispatch (Typer entry point)
# ---------------------------------------------------------------------------


def dispatch_inspectdb(
    *,
    output: Path | None = None,
    schema: str = "public",
) -> None:
    """Synchronous CLI entry-point: delegates to :func:`run_inspectdb`."""
    exit_code = asyncio.run(run_inspectdb(output=output, schema=schema))
    if exit_code != 0:
        raise typer.Exit(code=exit_code)
