"""``ferrum makemigrations`` command: generate migration files from model state.

Scans the existing migrations directory to reconstruct the virtual DB schema
state, diffs it against the current model registry, and writes a new
``NNNN_<slug>.py`` migration file when there are changes.

No database connection is required.  The plan is computed by comparing model
metadata (built once at class-definition time) against the schema state implied
by the sequence of previously generated migrations (static analysis only).
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any

import typer
from rich import print as rprint

if TYPE_CHECKING:
    from ferrum.models import Model

from ferrum.migrations import loader
from ferrum.migrations.orchestrator import compute_plan

_MIGRATION_TEMPLATE = """\
# Generated by ferrum makemigrations
from ferrum.migrations import Migration
from ferrum.migrations import operations as ops


class Migration(Migration):
    dependencies = {dependencies!r}

    operations = [
{operations_source}
    ]
{reverse_operations_block}"""


def _get_all_model_subclasses() -> list[type[Model]]:
    """Return all concrete Model subclasses visible in the current process.

    Traverses the full ``__subclasses__()`` tree so that models defined in
    nested packages are found.  Only classes whose ``ModelMetadata`` was built
    (i.e. that have at least one field) are included.
    """
    from ferrum.models import Model

    result: list[type[Model]] = []
    stack = list(Model.__subclasses__())
    while stack:
        cls = stack.pop()
        if getattr(cls, "__ferrum_metadata__", None) is not None:
            result.append(cls)
        stack.extend(cls.__subclasses__())
    return result


def _build_existing_state(
    migrations: list[loader.MigrationModule],
) -> dict[str, list[str]]:
    """Replay prior migration operations to produce {table: [column_names]} state.

    This is a static reconstruction — no database connection is used.  Only
    ``create_table``, ``add_column``, ``drop_table``, and ``drop_column`` ops
    are handled because those are the only kinds that change the column
    inventory tracked by ``compute_plan``.
    """
    state: dict[str, list[str]] = {}
    for mig_mod in migrations:
        for op in mig_mod.migration.operations:
            op_dict = op.to_op_dict()
            kind = op_dict.get("kind")
            if kind == "create_table":
                table = op_dict["table"]
                state[table] = [c["name"] for c in op_dict.get("columns", [])]
            elif kind == "add_column":
                table = op_dict["table"]
                state.setdefault(table, []).append(op_dict["name"])
            elif kind == "drop_table":
                state.pop(op_dict.get("table", ""), None)
            elif kind == "drop_column":
                table = op_dict.get("table", "")
                col = op_dict.get("column", "")
                if table in state and col in state[table]:
                    state[table].remove(col)
    return state


def _col_source(col: dict[str, Any]) -> str:
    """Render a column-def dict as an ``ops.Column(...)`` source expression."""
    flags: list[str] = []
    if col.get("not_null"):
        flags.append("not_null=True")
    if col.get("primary_key"):
        flags.append("primary_key=True")
    if col.get("default") is not None:
        flags.append(f"default={col['default']!r}")
    extra = (", " + ", ".join(flags)) if flags else ""
    return f"ops.Column({col['name']!r}, {col['sql_type']!r}{extra})"


def _index_source(op: dict[str, Any]) -> str:
    """Render an ``add_index`` plan op as an ``ops.AddIndex(...)`` expression."""
    flags: list[str] = []
    if op.get("unique"):
        flags.append("unique=True")
    using = op.get("using", "btree")
    if using != "btree":
        flags.append(f"using={using!r}")
    if op.get("where") is not None:
        flags.append(f"where={op['where']!r}")
    opclasses = op.get("opclasses")
    if opclasses:
        flags.append(f"opclasses={list(opclasses)!r}")
    extra = (", " + ", ".join(flags)) if flags else ""
    columns = [repr(c) for c in op.get("columns", [])]
    cols_arg = ", ".join(columns)
    return f"ops.AddIndex({op['table']!r}, {op['name']!r}, [{cols_arg}]{extra})"


def _op_to_source(op: dict[str, Any]) -> str:
    """Convert a plan op dict to an 8-space-indented Python source line.

    Handles ``create_table``, ``add_column``, ``add_index``, and ``add_fk`` — the kinds
    emitted by ``compute_plan`` in v0.1.

    Raises:
        ValueError: if the op kind cannot be rendered to Python source.
    """
    kind = op.get("kind", "")

    if kind == "create_table":
        table = op["table"]
        col_lines = [f"            {_col_source(c)}," for c in op.get("columns", [])]
        if col_lines:
            cols_block = "\n".join(col_lines)
            return f"        ops.CreateTable({table!r}, [\n{cols_block}\n        ]),"
        return f"        ops.CreateTable({table!r}, []),"

    if kind == "add_column":
        table = op["table"]
        col: dict[str, Any] = {
            "name": op["name"],
            "sql_type": op["sql_type"],
            "not_null": op.get("not_null", False),
            "default": op.get("default"),
            "primary_key": op.get("primary_key", False),
        }
        return f"        ops.AddColumn({table!r}, {_col_source(col)}),"

    if kind == "add_index":
        return f"        {_index_source(op)},"

    if kind == "add_fk":
        return (
            f"        ops.AddForeignKey({op['table']!r}, {op['name']!r}, "
            f"{op['column']!r}, {op['ref_table']!r}, {op.get('ref_column', 'id')!r}, "
            f"on_delete={op.get('on_delete', 'CASCADE')!r}),"
        )

    raise ValueError(f"Cannot render op kind {kind!r} to Python source")


def _reverse_op_to_source(op_dict: dict[str, Any]) -> str | None:
    """Return the 8-space-indented source line for the reverse of *op_dict*, or
    ``None`` if the operation has no safe auto-reverse.

    Reversible ops:
    - ``create_table`` → ``ops.DropTable(table)``
    - ``add_column``   → ``ops.DropColumn(table, col)``
    - ``add_index``    → ``ops.DropIndex(name)``
    - ``add_fk``       → ``ops.DropForeignKey(table, name)``

    Everything else (``drop_table``, ``drop_column``, ``drop_index``,
    ``rename_column``, ``raw_sql``, ``drop_fk``) returns ``None``.
    """
    kind = op_dict.get("kind", "")
    if kind == "create_table":
        return f"        ops.DropTable({op_dict['table']!r}),"
    if kind == "add_column":
        return f"        ops.DropColumn({op_dict['table']!r}, {op_dict['name']!r}),"
    if kind == "add_index":
        return f"        ops.DropIndex({op_dict['name']!r}),"
    if kind == "add_fk":
        return f"        ops.DropForeignKey({op_dict['table']!r}, {op_dict['name']!r}),"
    return None


def _build_reverse_block(ops: list[dict[str, Any]]) -> str:
    """Build the ``reverse_operations = [...]`` class body block.

    Returns a string that starts with a newline so it can be appended directly
    after the closing ``]`` of the ``operations`` list in the migration template.
    If any op has no known reverse, the block uses the irreversible-comment form
    with an empty list so the developer can fill it in manually.
    """
    rev_lines = [_reverse_op_to_source(op) for op in ops]
    has_irreversible = any(line is None for line in rev_lines)
    if has_irreversible:
        return (
            "\n    # WARNING: one or more operations cannot be auto-reversed.\n"
            "    # Populate reverse_operations manually or leave empty to mark"
            " this migration irreversible.\n"
            "    reverse_operations = []\n"
        )
    joined = "\n".join(line for line in rev_lines if line is not None)
    return f"\n    reverse_operations = [\n{joined}\n    ]\n"


async def run_makemigrations(
    migrations_dir: Path,
    name: str | None = None,
) -> int:
    """Generate a new migration file from current model state.

    Scans *migrations_dir* for existing migrations to determine the virtual DB
    state, computes a diff against the current model registry, and writes a new
    ``NNNN_<slug>.py`` file when there are pending changes.

    Args:
        migrations_dir: Directory to scan for existing migrations and write the
            new file into.  Created if it does not exist.
        name: Optional slug for the migration file name.  Defaults to ``"auto"``.

    Returns:
        ``0`` — migration file written successfully.
        ``1`` — no changes detected; nothing written.
        ``2`` — error (details printed to stderr).
    """
    try:
        existing_migrations = loader.scan(migrations_dir)
    except ValueError as exc:
        print(f"Error: failed to scan migrations directory: {exc}", file=sys.stderr)
        return 2

    existing_state = _build_existing_state(existing_migrations)
    model_classes = _get_all_model_subclasses()

    plan = compute_plan(model_classes, existing_state)
    ops = plan.get("ops", [])

    if not ops:
        print("No changes detected.")
        return 1

    if existing_migrations:
        last_name = existing_migrations[-1].name
        last_seq = int(last_name[:4])
        next_seq = last_seq + 1
        dependencies: list[str] = [last_name]
    else:
        next_seq = 1
        dependencies = []

    slug = name if name is not None else "auto"
    filename = f"{next_seq:04d}_{slug}.py"

    try:
        ops_source = "\n".join(_op_to_source(op) for op in ops)
    except ValueError as exc:
        print(f"Error: cannot render migration ops to source: {exc}", file=sys.stderr)
        return 2

    reverse_block = _build_reverse_block(ops)

    content = _MIGRATION_TEMPLATE.format(
        dependencies=dependencies,
        operations_source=ops_source,
        reverse_operations_block=reverse_block,
    )

    migrations_dir.mkdir(parents=True, exist_ok=True)
    dest = migrations_dir / filename
    dest.write_text(content, encoding="utf-8")

    rprint(f"[green]Created[/green] {dest}")
    return 0


def makemigrations(
    *,
    name: str | None = None,
    migrations_dir: Path | None = None,
) -> None:
    """Sync CLI entry-point: delegate to :func:`run_makemigrations`."""
    path = migrations_dir or loader.migrations_dir_default()
    exit_code = asyncio.run(run_makemigrations(path, name))
    if exit_code != 0:
        raise typer.Exit(code=exit_code)
